name: ds_ads
description: Ads SectDev components for Flutter projects (https://sect.dev/). Supports AdMob and AppLovin mediations
version: 0.8.0
repository: https://github.com/al-tush/ds_ads

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  fimber: ^0.7.0
  ds_common: ^0.1.11
  freezed_annotation: ^2.1.0
  collection: ^1.16.0

  google_mobile_ads: ^5.1.0

  applovin_max: ^3.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: pro.altush.ads.ds_ads
        pluginClass: DsAdsPlugin
